import { defineTool } from '@deepseek-ai/dsh-tools'
import { readFile, stat } from 'node:fs/promises'
import JSZip from 'jszip'
import { XMLParser } from 'fast-xml-parser'
export const name='chatcath-artifact-viewer'
export const inject=['tools']
const MAX=25*1024*1024,parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',textNodeName:'#text',removeNSPrefix:true,parseTagValue:false})
const array=x=>x===undefined?[]:Array.isArray(x)?x:[x]
const textOf=x=>{if(x==null)return'';if(typeof x==='string')return x;if(typeof x!=='object')return String(x);if(typeof x['#text']==='string')return x['#text'];return Object.entries(x).filter(([k])=>!k.startsWith('@_')).flatMap(([,v])=>array(v)).map(textOf).join('')}
const basename=p=>p.split('/').pop()||p
const extname=p=>{const n=basename(p),i=n.lastIndexOf('.');return i<0?'':n.slice(i).toLowerCase()}
const ids=p=>'artifact:'+p
function typeOf(p){const e=extname(p);if(['.fa','.fasta','.faa','.fna','.fas'].includes(e))return'fasta';if(e==='.csv')return'csv';if(e==='.tsv')return'tsv';if(e==='.docx')return'docx';if(e==='.pptx')return'pptx';if(e==='.pdf')return'pdf';return'text'}
function parseFasta(text){const records=[];let r=null;for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line)continue;if(line.startsWith('>')){if(r)records.push(r);const h=line.slice(1),i=h.search(/\s/);r={id:i<0?h:h.slice(0,i),description:i<0?'':h.slice(i).trim(),sequence:''}}else if(r)r.sequence+=line.replace(/\s/g,'').toUpperCase()}if(r)records.push(r);return records.map(x=>({...x,length:x.sequence.length}))}
function parseDelimited(text,sep){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(quote){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quote=false;else cell+=c}else if(c==='"')quote=true;else if(c===sep){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const header=rows.shift()||[];return{header,rows:rows.slice(0,10000),truncated:rows.length>10000,totalRows:rows.length}}
function parseDocxXml(xml){const body=parser.parse(xml).document?.body||{},blocks=[];for(const [kind,value] of Object.entries(body)){if(kind==='p')for(const p of array(value)){const style=p.pPr?.pStyle?.['@_val']||'',text=textOf(p).trim();if(text)blocks.push({type:'paragraph',style,text})}else if(kind==='tbl')for(const tbl of array(value)){const rows=array(tbl.tr).map(tr=>array(tr.tc).map(tc=>textOf(tc).trim()));if(rows.length)blocks.push({type:'table',rows})}}return{blocks}}
async function parseDocx(buffer){const zip=await JSZip.loadAsync(buffer),file=zip.file('word/document.xml');if(!file)throw new Error('invalid DOCX: word/document.xml missing');return parseDocxXml(await file.async('string'))}
function shapeBlocks(tree){return [...array(tree?.sp),...array(tree?.graphicFrame)].map((s,i)=>{const xfrm=s.spPr?.xfrm||s.xfrm||{},off=xfrm.off||{},ext=xfrm.ext||{};return{id:i,text:textOf(s.txBody||s).trim(),x:+off['@_x']||0,y:+off['@_y']||0,w:+ext['@_cx']||0,h:+ext['@_cy']||0}}).filter(x=>x.text)}
async function parsePptx(buffer){const zip=await JSZip.loadAsync(buffer),names=Object.keys(zip.files).filter(x=>/^ppt\/slides\/slide\d+\.xml$/.test(x)).sort((a,b)=>(+a.match(/\d+/)[0])-(+b.match(/\d+/)[0])),slides=[];for(const name of names){const tree=parser.parse(await zip.file(name).async('string')).sld?.cSld?.spTree||{};slides.push({number:slides.length+1,blocks:shapeBlocks(tree),text:textOf(tree).trim()})}if(!slides.length)throw new Error('invalid PPTX: no slides');return{slides}}
async function inspect(path){const s=await stat(path);if(!s.isFile())throw new Error('not a file');if(s.size>MAX)throw new Error(`file too large (${s.size} bytes, max ${MAX})`);const type=typeOf(path),a={id:ids(path),path,name:basename(path),type,size:s.size,summary:'',data:null};if(type==='fasta'){const rs=parseFasta(await readFile(path,'utf8'));a.data={records:rs};a.summary=`${rs.length} sequences · ${rs.reduce((n,r)=>n+r.length,0)} residues`}else if(type==='csv'||type==='tsv'){const d=parseDelimited(await readFile(path,'utf8'),type==='csv'?',':'\t');a.data=d;a.summary=`${d.totalRows} rows · ${d.header.length} columns`}else if(type==='docx'){a.data=await parseDocx(await readFile(path));a.summary=`Word document · ${a.data.blocks.length} blocks`}else if(type==='pptx'){a.data=await parsePptx(await readFile(path));a.summary=`PowerPoint · ${a.data.slides.length} slides`}else if(type==='pdf'){a.summary='PDF document'}else{const text=await readFile(path,'utf8');a.data={text:text.slice(0,500000),truncated:text.length>500000};a.summary=`${text.length} characters`}return a}
export function apply(ctx){ctx.tools.register(defineTool({name:'artifact_cards',description:'Render local FASTA, CSV/TSV, DOCX, PPTX, PDF, or text files as a card grid in chat; clicking opens an interactive right-side preview.',parameters:{paths:{type:'array',required:true,items:{type:'string'}}},output:{schema:{type:'object',additionalProperties:true},render:(_a,v)=>[{type:'text',text:JSON.stringify({kind:'dsh-artifact-cards',entries:v.entries})}]},async execute(args){const list=[];for(const p of args.paths)list.push(await inspect(p));return{files:list.map(x=>x.name),count:list.length,entries:list}}}))}
