import React, { useEffect, useRef, useState } from 'react'

let molstarPromise
const store={ active:null, listeners:new Set(), set(v){this.active=v;this.listeners.forEach(f=>f())}, close(){this.active=null;this.listeners.forEach(f=>f())} }
const api=async url=>{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function loadMolstar(){if(molstarPromise)return molstarPromise;molstarPromise=new Promise((ok,no)=>{if(window.molstar)return ok(window.molstar);if(!document.querySelector('[data-protein-molstar-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://cdn.jsdelivr.net/npm/molstar@5.11.0/build/viewer/molstar.css';l.dataset.proteinMolstarCss='1';document.head.appendChild(l)}const existing=document.querySelector('[data-protein-molstar-js]');if(existing){existing.addEventListener('load',()=>ok(window.molstar));return}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/molstar@5.11.0/build/viewer/molstar.js';s.dataset.proteinMolstarJs='1';s.onload=()=>ok(window.molstar);s.onerror=()=>no(new Error('Mol* CDN load failed'));document.head.appendChild(s)});return molstarPromise}
const call=(name,args)=>({head:{name},args}),prop=n=>call('structure-query.atom-property.macromolecular.'+n,{}),eq=(a,b)=>call('core.rel.eq',[a,b]),group=x=>call('structure-query.generator.atom-groups',x),merge=x=>x.length===1?x[0]:call('structure-query.combinator.merge',x)
const chainExpr=ids=>merge(ids.map(id=>group({'chain-test':eq(prop('auth_asym_id'),id)})))
const residueExpr=rs=>merge(rs.map(r=>group({'chain-test':eq(prop('auth_asym_id'),r.chain),'residue-test':eq(prop('auth_seq_id'),r.resSeq)})))
async function loadStyled(viewer,d,text){const p=viewer.plugin,r=d.style,raw=await p.builders.data.rawData({data:text,label:d.name}),traj=await p.builders.structure.parseTrajectory(raw,'pdb'),model=await p.builders.structure.createModel(traj,{modelIndex:0}),root=await p.builders.structure.createStructure(model,{name:'model',params:{}});async function add(expr,key,type,color){const c=await p.builders.structure.tryCreateComponentFromExpression(root,expr,key,{label:key});if(c)await p.builders.structure.representation.addRepresentation(c,{type,color:color==='chain'?'chain-id':'uniform',colorParams:color==='chain'?{}:{value:color},typeParams:{alpha:.6}})}if(r.antigenChains.length)await add(chainExpr(r.antigenChains),'Antigen',r.antigenRepresentation==='surface'?'molecular-surface':r.antigenRepresentation,0x9bbbd5);if(r.antibodyChains.length)await add(chainExpr(r.antibodyChains),'Antibody',r.antibodyRepresentation,'chain');if(r.epitopeResidues.length){await add(residueExpr(r.epitopeResidues),'Selected residues','ball-and-stick',parseInt(r.epitopeColor.slice(1),16));viewer.structureInteractivity({elements:{items:r.epitopeResidues.map(x=>({auth_asym_id:x.chain,auth_seq_id:x.resSeq}))},action:['select','focus']})}}
function Thumbnail({d}){const ref=useRef();useEffect(()=>{const c=ref.current,pts=[];d.chains.forEach(x=>x.residues.forEach(y=>pts.push(y)));if(!c||!pts.length)return;const w=c.width=c.clientWidth||220,h=c.height=120,g=c.getContext('2d');let X=0,Y=0;pts.forEach(q=>{X+=q.x;Y+=q.y});X/=pts.length;Y/=pts.length;let radius=1;pts.forEach(q=>radius=Math.max(radius,Math.hypot(q.x-X,q.y-Y)));const k=Math.min(w,h)*.4/radius;g.clearRect(0,0,w,h);let n=0;d.chains.forEach(ch=>{let last;ch.residues.forEach(q=>{const now={x:w/2+(q.x-X)*k,y:h/2-(q.y-Y)*k};if(last){g.strokeStyle=`hsl(${215-215*n/pts.length} 80% 55%)`;g.lineWidth=2;g.beginPath();g.moveTo(last.x,last.y);g.lineTo(now.x,now.y);g.stroke()}last=now;n++})})},[d]);return <canvas ref={ref} className="pc-thumb"/>}
function Molstar({d}){const ref=useRef(),viewer=useRef();const[msg,setMsg]=useState('加载 Mol*…');useEffect(()=>{let dead=false;loadMolstar().then(async m=>{const v=await m.Viewer.create(ref.current,{layoutIsExpanded:false,layoutShowControls:true,layoutShowSequence:true,layoutShowLeftPanel:false,layoutShowLog:false,viewportShowExpand:false,viewportShowSelectionMode:true});viewer.current=v;const z=await api('/api/protein-cards/text/'+encodeURIComponent(d.id));if(d.style.antigenChains.length)await loadStyled(v,d,z.text);else await v.loadStructureFromData(z.text,'pdb');if(!dead)setMsg('点击结构或序列残基可双向联动')}).catch(e=>!dead&&setMsg('Mol* 错误：'+e.message));return()=>{dead=true;if(viewer.current)try{viewer.current.dispose()}catch{}}},[d.id]);return <div className="pc-ms-wrap"><div ref={ref} className="pc-ms"/><small>{msg}</small></div>}
function Drawer(){const[,tick]=useState(0);useEffect(()=>{const f=()=>tick(x=>x+1);store.listeners.add(f);return()=>store.listeners.delete(f)},[]);const d=store.active;if(!d)return null;return <div className="pc-overlay" onClick={e=>e.target===e.currentTarget&&store.close()}><aside className="pc-drawer"><header><div><b>{d.name}</b><small>{d.title}</small></div><button onClick={()=>store.close()}>✕</button></header><main><Molstar d={d}/><section><h3>Description</h3>{String(d.description||d.title||'暂无描述').split('\n').map((x,i)=><p key={i}>{x}</p>)}</section></main></aside></div>}
function Grid(props){const[data,setData]=useState(null);useEffect(()=>{let live=true,n=0;const go=()=>api('/api/protein-cards/call/'+encodeURIComponent(props.callId)).then(r=>{if(!live)return;r.entries.length?setData(r.entries):n++<40&&setTimeout(go,300)}).catch(()=>n++<40&&setTimeout(go,300));go();return()=>{live=false}},[props.callId]);if(!data)return <small>解析 PDB…</small>;return <div className="pc-grid">{data.map(d=><article className="pc-card" key={d.id} onClick={()=>store.set(d)}><Thumbnail d={d}/><div className="pc-info"><b>{d.name}</b><small>{d.title}</small><div className="pc-chips"><span>{d.total} aa</span><span>{d.chains.length} chains</span><span className="epi">{d.style.epitopeResidues.length} selected</span></div></div></article>)}</div>}
export const inject=['slots'];
export function apply(ctx){ctx.effect(()=>ctx.slots.inject('tool.call.toolview',()=>ctx.slots.register({name:'tool.call.toolview',key:'protein_cards'},Grid)));ctx.effect(()=>ctx.slots.inject('shell.overlay',()=>ctx.slots.register({name:'shell.overlay',id:'protein-cards-inspector',order:90},Drawer)));ctx.effect(()=>{const tag=document.createElement('style');tag.textContent=`.pc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:10px}.pc-card{overflow:hidden;border:1px solid #ffffff22;border-radius:12px;background:var(--dsw-alias-bg-layer-1,#19191f);cursor:pointer}.pc-card:hover{border-color:#4f8cff}.pc-thumb{display:block;width:100%;height:120px;background:radial-gradient(circle,#ffffff10,#0004)}.pc-info{padding:9px}.pc-info small{display:block;color:#999;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin:4px 0 8px}.pc-chips{display:flex;gap:5px}.pc-chips span{font-size:10px;border:1px solid #ffffff20;border-radius:20px;padding:2px 6px}.pc-chips .epi{color:#ff6666}.pc-overlay{position:fixed;inset:0;z-index:500;background:#0005}.pc-drawer{position:absolute;right:0;top:0;bottom:0;width:min(900px,56vw);min-width:560px;background:var(--dsw-alias-bg-base,#131318);border-left:1px solid #ffffff22;box-shadow:-12px 0 40px #0008;display:flex;flex-direction:column}.pc-drawer header{z-index:1002;display:flex;justify-content:space-between;gap:12px;padding:13px 16px;border-bottom:1px solid #ffffff20}.pc-drawer header small{display:block;color:#999}.pc-drawer header button{border:0;background:#ffffff12;color:#ddd;border-radius:6px;width:32px;height:32px;cursor:pointer}.pc-drawer main{padding:12px 16px 24px;overflow:auto}.pc-ms-wrap{border:1px solid #ffffff22;border-radius:10px;overflow:hidden}.pc-ms{position:relative;height:620px}.pc-ms .msp-plugin{position:absolute;inset:0}.pc-ms .msp-layout-right{display:none!important}.pc-ms .msp-layout-main,.pc-ms .msp-layout-top,.pc-ms .msp-layout-bottom{right:0!important}.pc-ms .msp-layout-bottom{left:0!important;width:auto!important}.pc-ms-wrap>small{display:block;padding:6px;color:#aaa}@media(max-width:900px){.pc-drawer{width:80vw;min-width:0}}`;document.head.appendChild(tag);return()=>tag.remove()})}
